Epmgcipgab 38 language switcher
epam/epmgcip-gabt.user-app pull request #13
Opened 2024-08-14 10:40 UTC by suren-tadevosyan

2024-08-19 02:30 UTC, andreyBalabukha requested changes

2024-08-19 02:30 UTC, andreyBalabukha commented on src/components/buttons/menu-buttn/index.tsx
> +        alt={isOpen ? "Close menu" : "Open menu"}
Please move to literals

2024-08-19 02:30 UTC, andreyBalabukha commented on src/components/buttons/menu-buttn/index.tsx
> +      <span className={textClassName}>{isOpen ? "Close" : "MENU"}</span>
Please move to literals

2024-08-19 09:42 UTC, suren-tadevosyan commented on src/components/buttons/menu-buttn/index.tsx
> +        alt={isOpen ? "Close menu" : "Open menu"}
done

2024-08-20 01:45 UTC, andreyBalabukha approved these changes

2024-08-20 01:45 UTC, merged